"""chat id for user state

Revision ID: 1e0b99292638
Revises: 6e7a0b3e5221
Create Date: 2025-01-13 21:22:35.236948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0b99292638'
down_revision: Union[str, None] = '6e7a0b3e5221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_states', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_states', 'chat_id')
    # ### end Alembic commands ###
